version: 2.1

# Define the jobs we want to run for this project
jobs:
  unit_test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          name: run unit tests
          command: make test
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          name: build go app
          command: make build

# Orchestrate our job run sequence
workflows:
  version: 2
  test_and_release:
    jobs:
      - unit_test:
          name: Unit tests
      - build:
          name: Build
          requires:
            - Lint
            - Unit tests
